### ISSUE TITLE
Code Typo

### ISSUE THREAD

**Issue by TengMaGH** [MDIL-SNU/SIMPLE-NN_v2#103]
**File destination:** [https://github.com/MDIL-SNU/SIMPLE-NN_v2/tree/main/simple_nn/features/symmetry_function/generating.py](https://github.com/MDIL-SNU/SIMPLE-NN_v2/tree/main/simple_nn/features/symmetry_function/generating.py)
**Location:** Line 113, Line 118.
**Change:** logfie --> logfile

**Comment by JisuJung928** [comment]
Dear Teng-Martin-Ma,

I really appreciate your help!
We will correct them as soon as possible.

Thanks!

Best regards,
Jisu.
