### ISSUE TITLE
Parameter total_iteration and save_criteria not working!

### ISSUE THREAD

**Issue by aishwaryo** [MDIL-SNU/SIMPLE-NN_v2#106]
I am working with Simple-NN. The options save_criteria and total_iteration is giving warning as  : "**Warning: Unidentified option in neural_network: total_iteration**" and "**Warning: Unidentified option in neural_network: save_criteria**" . I am attaching the input.yaml file too. Please let me know if there is something wrong done by me. 

```
generate_features: False
preprocess: False
train_model: True
random_seed: 123
params:
   Ti: params_Ti
   Al: params_Al
   C:  params_C

neural_network:
    nodes: 30-30
    batch_size: 64
    optimizer:  
       method: Adam 
    total_epoch: 4000

    learning_rate: 0.001
    use_scale: True
    use_pca: True
    use_stress: False
    use_force : True
    save_interval : 0
    show_interval : 100
    break_max : 10
    total_iteration : -2000000    
    save_criteria : v_F,v_E
    
    acti_func : tanh
    
```

**Comment by mind-dime** [comment]
Hi Jisu. I actually looked up these parameters from the documentation page itself. These parameters are mentioned there for early stopping?

https://simple-nn-v2.readthedocs.io/en/latest/models/hdnn/hdnn.html

**Comment by JisuJung928** [comment]
Yes, they are mentioned for early stopping, but the page you sent me is deprecated. I'm sorry. I'm sure that [this page](https://simple-nn-v2.readthedocs.io/en/latest/inputs/input.yaml/neural_network/neural_network.html) contains the information you need.
Can you explain how you found that page? We should modify them.

Best regards,
Jisu

**Comment by mind-dime** [comment]
I was searching for early stopping with epoch delay in the SIMPLENN readthedocs  when I found this link. So currently there is no support for early stopping alongside epoch delay in SIMPLENN?

**Comment by JisuJung928** [comment]
We still provide early stopping techniques through the `energy_criteria` and `force_ceriteria` options. Please visit [here](https://simple-nn-v2.readthedocs.io/en/latest/inputs/input.yaml/neural_network/energy_criteria.html) and [here](https://simple-nn-v2.readthedocs.io/en/latest/inputs/input.yaml/neural_network/force_criteria.html).

Thanks for letting me know about our deprecated page.

**Comment by mind-dime** [comment]
Thank you for your response!
