### ISSUE TITLE
Enabling installation in Windows (Following up issue #88)

### ISSUE THREAD

**Issue by LateButSteady** [MDIL-SNU/SIMPLE-NN_v2#113]
Problem
  - python setup.py install fails in windows OS
  - Error message:  error C3861: “sincos”: Could not find the identifier (Already reported in issue #88 )

Cause
  - The function "sincos" is only supported in Linux, not in Windows.

Is it okay that I modify the code to enable installation in Windows?
I will define the "sincos" function in the files below after detecting OS.
  - symmetry_functions.h
  - pair_nn_simd_function.h

**Comment by LateButSteady** [comment]
I submitted a Pull Request to solve this issue.

**Comment by JisuJung928** [comment]
Thank you for your contribution!

https://github.com/MDIL-SNU/SIMPLE-NN_v2/pull/114#issuecomment-1871676726
