### ISSUE TITLE
Evaluation/Inference with simple-NN

### ISSUE THREAD

**Issue by rschireman** [MDIL-SNU/SIMPLE-NN_v2#82]
Hi all,

I've greatly enjoyed using simple-NN and now I'm looking for a way to use the NNP in an external program different from lammps. I think an ASE calculator would be relatively easy to develop, but I don't see a function within the code that can take an ASE atoms object and do a forward pass through the network to obtain the NNP energies and forces (and maybe stress). The `calc_result` variable in the `test_model(inputs, logfile, model, optimizer, criterion, device, test_loader)` function returns the desired values, but I'm not familiar enough with the code to generate the symmetry function values for a given structure and apply the scaling factor, etc. I'm more than happy to develop the function, but I'm at a loss on where to start.

**Comment by JisuJung928** [comment]
Hi rschireman,

As far as I understand, what you want is to get NNP energies, forces, and stress from ASE atoms object directly.

In that case, I strongly recommend you to utilize the `lammpslib` in ASE calculator, not to evaluate by SIMPLE-NN for fast speed.

Although SIMPLE-NN provides the `test mode` for evaluation (see documentation), it requires `generate` and `preprocess` steps in advance. Those processes are good for training in terms of recyclability and efficient data loading but not suitable for instant `volatile` evaluation.

Best regards,
Jisu

**Comment by rschireman** [comment]
Hi Jisu,

The lammpslib interface in the ASE calculator works great! Thanks for your help.

Ray
