### ISSUE TITLE
PCA issue

### ISSUE THREAD

**Issue by vsumaria** [MDIL-SNU/SIMPLE-NN_v2#86]
I am facing the following error during preprocessing. 
ValueError: Number of [Pt] feature point[72] is less than input size[332]. This cause error during calculate PCA matrix

I am attaching the files here so that it's easier to recreate the error. 
[input.zip](https://github.com/MDIL-SNU/SIMPLE-NN_v2/files/8672932/input.zip)

I'm not sure what I am doing wrong.

**Comment by JisuJung928** [comment]
Hello, vsumaria.

PCA method in sklearn module provides the PCA matrix with rank of min(# of atomic environments. # of symmetry functions).
Therefore, error can occur when the # of symmetry function is larger than # of atomic environments.
Please reduce the # symmetry function or add the training set.

Best regards, Jisu.

**Comment by vsumaria** [comment]
Is there a way to estimate the time required or understand the progress of the PCA calculations step?

**Comment by JisuJung928** [comment]
Hello, vsumaria.

Here PCA caltulation step is.
https://github.com/MDIL-SNU/SIMPLE-NN_v2/blob/c2d73f3db5450bb6fe9bb02a760e7ec28a7381b7/simple_nn/features/preprocessing.py#L130
Also, I suggest this documentation page for detailed PCA progress.
https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
I believe that it is helpful for you to understand PCA calculation.

Best regards,
Jisu.
