### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Organicwrq** [MDIL-SNU/SIMPLE-NN_v2#88]
I can't install it by setup.py because of simple_nn\features\symmetry_function\symmetry_functions.h(76): error C3861: “sincos”: Could not find the identifier.I want know what is 'sincos' and how to slove the problem.Thank you.
![LM_B$A@)1@ OB3Q1$7EXIX](https://user-images.githubusercontent.com/75873382/173366130-9d120558-3cbb-480a-97f9-fd12c4339248.png)

And this is the relevant part of symmetry_functions.h.
![E@G45WWIEY_MW733R}4AP5L](https://user-images.githubusercontent.com/75873382/173366673-59095553-bf97-4825-a3a0-8a0fdffddc60.png)

**Comment by JisuJung928** [comment]
Hello, Organicwrq

Currently, SIMPLE-NN supports only the Linux operation systems.
If you use Windows OS, please use SIMPLE-NN through WSL (Windows Subsystem for Linux).

Best regards,
Jisu.

**Comment by LateButSteady** [comment]
@Phorbol, it seems that you are running the code in windows, which does not "sincos" function.
Here is an example code in symmetry_functions.h file to replace "sincos" function in windows. This works in the same with "sincos"

```c++
// sincos(M_PI*frac, &sin, &cos);
// f = 0.5 * (1 + cos);
// df = 0.5 * M_PI * sin / cutd;

sin_val = sin(M_PI*frac);
cos_val = cos(M_pi*frac);
f = 0.5 * (1 + cos_val);
df = -0.5 * M_PI * sin_val / cutd;
```
