### ISSUE TITLE
lammps complie failed

### ISSUE THREAD

**Issue by Teng-Martin-Ma** [MDIL-SNU/SIMPLE-NN_v2#96]
**System:** Linux (google colab)  
**Compilor:** mpicxx -g -O3 -std=c++11  -DLAMMPS_GZIP -DLAMMPS_MEMALIGN=64    -DMPICH_SKIP_MPICXX -DOMPI_SKIP_MPICXX=1  
**Issue:**  
../pair_nn_replica.cpp: In member function ‘virtual void LAMMPS_NS::PairREPLICA::init_style()’:
../pair_nn_replica.cpp:850:35: error: ‘int LAMMPS_NS::NeighRequest::half’ is protected within this context
     neighbor->requests[irequest]->half = 0;
                                   ^~~~
In file included from ../pair_nn_replica.cpp:30:0:
../neigh_request.h:55:7: note: declared protected here
   int half;    // half neigh list (set by default)
       ^~~~
../pair_nn_replica.cpp:851:35: error: ‘int LAMMPS_NS::NeighRequest::full’ is protected within this context
     neighbor->requests[irequest]->full = 1;
                                   ^~~~
In file included from ../pair_nn_replica.cpp:30:0:
../neigh_request.h:56:7: note: declared protected here
   int full;    // full neigh list
       ^~~~
Makefile:114: recipe for target 'pair_nn_replica.o' failed
make[1]: *** [pair_nn_replica.o] Error 1
make[1]: Leaving directory '/content/drive/MyDrive/lammps/src/Obj_mpi'
Makefile:378: recipe for target 'mpi' failed
make: *** [mpi] Error 2

**Comment by JisuJung928** [comment]
Hello, Teng-Martin-Ma

Please downgrade LAMMPS.
We are currently upgrading `pair_nn.cpp` and `pair_nn_replica.cpp` for new LAMMPS version.
Sorry for your inconvenience.

Best regards,
Jisu

**Comment by JisuJung928** [comment]
Hello, Teng-Martin-Ma

We just update the new `pair_nn.cpp` for the new LAMMPS version.
Please redownload and compile with it.

Best regards,
Jisu

**Comment by Teng-Martin-Ma** [comment]
Thanks. It works well now!
